
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("administracion.html", "Untitled Page", "untitled page perfiles calendario documentos tareas estado propietario mensajes contabilidad mantenimiento nombre del usuario lorem ipsum es simplemente el texto de relleno las imprentas archivos ha sido estándar industrias desde año cuando un impresor persona que se dedica la imprenta desconocido usó una galería textos los mezcló tal manera logró hacer libro especimen no sólo sobrevivió años sino tambien ingresó como en electrónicos quedando esencialmente igual al original fue popularizado con creación hojas quot letraset cuales contenian pasajes más recientemente software autoedición por ejemplo aldus pagemaker cual incluye versiones cargo pepitoperez email com teléfono móvil escoga pepito nuevo perfil cargar imagenes banner historial día actividad evento donde esta dirigido seleccione mi barrio edificio clasificado fecha realización titulo hora realizacion descripción am pm apartamento fiesta niños nbsp vendo arriendo garaje buscar aparace selecciona documento descripcion seleccion actas presupuesto circulares reclamento informes categoria sección recientes seccion archivo adjunto acta sobre asamblea pinta fachada color violeta imagen doc dolor sit amet consectetur adipiscing elit integer nec odio praesent libero sed cursus ante dapibus diam realizado autorizacion entrada ordenar reciente ascendente decendiente observacion pago ascendiente descendiente tipo propiedad administración titular detalle inmueble dia perez pecueca propio preaviso pecuecudo asunto nisi nulla quis sem at nibh elementum imperdiet duis sagittis mauris fusce tellus augue semper porta massa habitante bandeja salida nuevos seleccionar balances mensuales contables mensual presupuestos maximo caracteres octubre balance mes junio informe contable noviembre cotizacion costos arreglos areas locales estadisiticas especificaciones técnicas modelo marca fabricante adquicision ultima patico ltda su culpa observaciones proxima realizo costo equipo activo hidraulicos equipos seguridad ", "");
   this[database_length++] = new SearchPage("detalleabitanteadministra.html", "Untitled Page", "untitled page añadir personas detalle persona tipo nombre nbsp propietaria pepita getrudis samper mendoza eliminar mascota roxco nombres apellidos seleccione hermano propietario padres propietarios escolta servicio domestico otros arriendo especificque marca placa automovil renault nad1232 bicicleta bici no na vehiculos vehiculo selecione moto ", "");
   this[database_length++] = new SearchPage("detalleequipo.html", "Untitled Page", "untitled page fecha de mantenimiento próximo datos equipo especificaciones técnicas modelo marca fabricante adquicision ultima su culpa patico ltda observacion lorem ipsum dolor sit amet consectetur adipiscing elit integer nec odio praesent libero sed cursus ante dapibus diam nisi nulla quis sem at nibh elementum imperdiet duis sagittis mauris fusce tellus augue semper porta massa vestibulum lacinia arcu eget class aptent taciti sociosqu ad litora torquent per conubia nostra inceptos himenaeos curabitur sodales ligula in observaciones costo del estado activo fuera servicio ", "");
   this[database_length++] = new SearchPage("detallecontabilildad.html", "Untitled Page", "untitled page fecha tipo titulo adjuntos presupuesto no realizado para pintar el edificio archivo doc xls balance mensual de enero nbsp actas asambleas acta asamblea realizada hacer un parque subterraneo historial contable ", "");
   this[database_length++] = new SearchPage("editarpefil.html", "editarperfil", "editarperfil editar perfil nombre apellido número de documento seleccione registro civil tarjeta identidad cedulade ciudadania pasaporte otros tipo identificación correo electrónico femenino masculino sexo secundario teléfono móvil empresa dirección la contacto personal cargo fecha nacimiento fotografia archivos png gif jpg bmp tamaño máximo x345pixeles ", "");
   this[database_length++] = new SearchPage("historial_calendario.html", "Untitled Page", "untitled page fecha actividad hora apartamento fiesta de disfraces pm reunion alcholicos anonimos am padres familia asamblea consejo torre torre1 arreglos locativos administracion ", "");
   this[database_length++] = new SearchPage("historial_de_clasificados.html", "Untitled Page", "untitled page fecha clasificado teléfono apartamento vendo auto chevlolet finca en la sierra nevada arriendo garaje sillo torre1 edificio administracion ", "");
   this[database_length++] = new SearchPage("historial_documentos.html", "Untitled Page", "untitled page fecha tipo de documento hora archivos adjuntos acta asamblea pm adjuntoimagen documentos presupuesto am adjunto imagen circular no reclamento actualización ", "");
   this[database_length++] = new SearchPage("observaciones.html", "Untitled Page", "untitled page observación observaciones tareas autorizacion entrada persona lorem ipsum dolor sit amet consectetur adipiscing elit integer nec odio praesent libero sed cursus ante dapibus diam ", "");
   this[database_length++] = new SearchPage("detallepropiedad.html", "Untitled Page", "untitled page detalle interno inmueble historial del añadir estado selecione otros habitable desabiltable seleccione casa apartamento pethause lote tipo de vivienda baños alcobas lorem ipsum es simplemente el texto relleno las imprentas archivos ha sido estándar industrias desde año cuando un impresor persona que se dedica la imprenta desconocido usó una galería textos los mezcló tal manera logró hacer libro especimen no sólo sobrevivió años sino tambien ingresó como en documentos electrónicos quedando esencialmente igual al original fue popularizado con creación hojas quot letraset cuales contenian pasajes más recientemente software autoedición por ejemplo aldus pagemaker cual incluye versiones especifique area habitado m3 dos palmas si ", "");
   this[database_length++] = new SearchPage("redactar.html", "Untitled Page", "untitled page redactar para copia asunto mensaje ", "");
   this[database_length++] = new SearchPage("equpodetallehistorial.html", "Untitled Page", "untitled page fecha tipo equipo observacion precio mantenimiento moto bomba aguas residuales lorem ipsum es simplemente el texto de relleno las imprentas archivos ha sido estándar industrias desde año cuando un impresor del persona que se dedica la imprenta desconocido usó una galería textos los mezcló tal manera logró hacer libro especimen no sólo sobrevivió años sino tambien ingresó como en documentos electrónicos quedando esencialmente igual al original fue popularizado con creación hojas quot letraset cuales contenian pasajes más recientemente software autoedición por ejemplo aldus pagemaker cual incluye versiones residualesl historial nbsp ", "");
   return this;
}
